### ISSUE TITLE
图论 第一章 第11题 答案错误

### ISSUE THREAD

**Issue by Tziheng** [sakura0423/USTC_Graph_Theory#3]
问题：构造以一个二分图G，使得G不与任何K维立方体的子图同构。其中，k为任意正整数。
原答案：K_{1,k+1}

错误理由：k是个任意数。
我的答案：考虑到K维立方体是个平面图，直接构造一个不是平面图的二分图即可，例如完全二分图K_{114,514}
​

**Comment by sakura0423** [comment]
thanks
